# Config file for automatic testing at travis-ci.org
sudo: false

language: python

cache: pip

python: 3.6

matrix:
  fast_finish: true

# Addons
addons:
  sonarcloud:
    organization: "openexo"

# install dependencies
install: pip install -r requirements_test.txt

# run tests on every Python version with tox
script: 
  - tox
  - sonar-scanner

# pypi deployment
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: marfyl
  password: 
    secure: "NWYIZ8eHEy9ewz4xvek+x3xIXooADLFjR+4s0ZMmGEDJIRpKPjjzkz5ZaN65VbPOHhGwkc5uqc6i+ECCa0vlRSwz0PinvomdvBWx8+gVsZxb+VkhktFatu2cYes0rLOGR+XqvDGr+XHAFIXD0jBx/Lq4VgwN4rXR37kqLhueTxOjD6vjPVwm77kX9SKWM5OQowDxEvwoBXZ9ArinQbq8rOapp5d72yJ5zfn3D4x5ef/B+jACoObaPmTxs6E5x4wue73JY6TUkJ+fkh3UH+dUVDQSJnREYF65Bx6feSHdEwqtu8KL9u0sdqasiSP2MLsAEhByxQ2nPiyhZJqh0/8fLj1GZREwiut156zx6K/Xv396pS2Q1iq9pmFfZmnglIjzPoyMdakJpbZWd5f2zNT4GQG4fp6ojSY7jSoJbg+61Fsq9Je0+8zGoX5B/qXz7P7bA3gI1s3V81JTwVKjfH0jWj/ia6Fn/XJ7QJy/k4DLS52J1N3zR4BinzvEQ4VGvFHRD8Swl+5sgx0WbMRM/oJckGSTvjLKruMYcZHVrcRET990pp7K6PJPIKoT7OH4HZMtI2QpC/a8xL1DOMoH5Lk86Fw/9V7IQPwNe9f/G0eUZ5GeSCkCQBX+8zl2OzklsWLNuWzdF78x/tubKwevQ2UogXB5VqpsxPO0onC++FVQ42I="
  on:
    tags: true
    repo: exolever/django-stats-redis
    python: 3.6

after_success:
  - codecov
